secureMailApp/authentication/urls.py
from django.urls import path
from . import views 

app_name = "authentication"

urlpatterns = [
    path("",views.register,name="register"),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
    # path("msg", views.msg, name="msg")
]

secureMailApp/main/urls.py
from django.urls import path
from . import views 

from .views import mainpage,successView, recview

app_name = "main"

urlpatterns = [

    # path("main",views.mainpage,name="main"),
    path("main/", mainpage, name="main"),
    path("success/", successView, name="success"),
    path("rec/", recview, name="rec")

]

secureMailApp/secureMailApp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('authentication.urls')),
    path('',include('main.urls')),
    path('admin/', admin.site.urls),
]

secureMailApp/authentication/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser

from .managers import CustomUserManager

# Create your models here.
class sysuser(AbstractUser):

    username = None
    email = models.EmailField(_('email address'),unique=True)
    publickey = models.CharField(max_length=255)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    objects = CustomUserManager()

    def __str__(self):
        return self.email

secureMailApp/authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from authentication.models import sysuser

from Crypto import Random
from Crypto.PublicKey import RSA
import base64
import smtplib, ssl

class NewUserForm(UserCreationForm):
    class Meta:
        model = sysuser
        fields = ("email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)

        modulus_length = 256*4 
        privatekey = RSA.generate(modulus_length, Random.new().read) 
        publickey = privatekey.publickey()

        f = open("private"+user.email+".pem", "wb")
        f.write(privatekey.exportKey(format='PEM',passphrase=self.cleaned_data.get("password1")))
        f.close()

        f = open ("public.pem", "wb")
        publickey = publickey.exportKey(format='OpenSSH')
        f.write(publickey)
        f.close()
        
        user.email = self.cleaned_data["email"]
        user.publickey = publickey
        if commit:
            user.save()
        return user

secureMailApp/authentication/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# from .forms import MsgForm
from django.contrib.auth import login , logout, authenticate
from django.contrib import messages
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required

def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"New account created: {username}")
            login(request, user)
            return redirect("/main")

        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

            return render(request = request,
                          template_name = "authentication/register.html",
                          context={"form":form})

    form = NewUserForm
    return render(request = request,
                  template_name = "authentication/register.html",
                  context={"form":form})

def logout_request(request):
    logout(request)
    messages.success(request, "Logged out successfully!")
    return redirect("authentication:login")

def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            
            request.session['password'] = password
            request.session['username'] = username

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"You are now logged in as {username}")
                return redirect('/main')
            else:
                messages.info(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request = request,
                    template_name = "authentication/login.html",
                    context={"form":form})

# def msg(request):
#     form = MsgForm()
#     if request.method == 'POST':
#         form = MsgForm(request)
#         if form.is_valid():
#             password = request.session.get('password') 
#             sender_email = request.session.get('username')
#             form.save(request,sender_email, password)

#     return render(request=request,
#         template_name = "authentication/msg.html",
#         context={"form":form})

# def receive_msg(request):
#     pass

secureMailApp/authentication/templates/authentication/header.html
<head>
    {% load static %}
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

{% if messages %}
    {% for message in messages %}
        <script>M.toast({html:"{{message}}", displayLength:2000 ,classes:'blue rounded'} );</script>
    {% endfor %}  
{% endif %}

<nav>
    <!-- <div class="nav-wrapper">
        {% if user.is_authenticated %}
        <a style="float: right; margin-right: 50px;"  href="#" onClick="document.getElementById('logoutform').submit()">
           logout
        </a>
        <form id="logoutform" method="POST" action="{% url 'authentication:logout' %}">
            {% csrf_token %}
        {% endif %}
       
    </div> -->
    <p style = "font-family:Trebuchet MS, Helvetica, sans-serif;font-size:30px;font-style:italic; text-indent: 50px;"> ssm.com </p>

  </nav>
  <br/>
  <br/>
<body>

  {% block content %}
  {% endblock %}
</body>

secureMailApp/authentication/templates/authentication/login.html
{% extends 'authentication/header.html' %}

{% block content %}

    <div class="container">
        <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
              <button style="background-color:#ee6e73; color:rgb(255, 255, 255)" class="btn btn-outline-info" type="submit">Login</button>
        </form>
        Don't have an account? <a href="/" target="blank"><strong>Register Here</strong></a>.
    </div>
{% endblock %}

secureMailApp/authentication/templates/authentication/msg.html
<!-- {% extends 'authentication/header.html' %} -->


{% block content %}

<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <label for="rec_email">Receiver Email </label>
        <input id="rec_email" type="text" name="rec_email" value="{{ current_name }}">

        <label for="msg">Message </label>
        <input id="msg" type="text" name="msg" value="{{ current_name }}">
        
        <input type="submit" value="Send">
    </form>
 </div>

{% endblock %}

secureMailApp/authentication/templates/authentication/register.html
{% extends 'authentication/header.html' %}


{% block content %}

<div class="container">
    <form method="POST">
        
        {% csrf_token %}
        {{form.as_p}}
        <button style="background-color:#ee6e73; color:rgb(255, 255, 255)" class="btn btn-outline-info" type="submit">Sign Up</button>

    </form>

        If you have already an account , <a href="/login"><strong>Login</strong></a> instead.
 </div>

{% endblock %}